apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aqis
spec:
  rules:
    - host: aqis.internal.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aqis-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: aqis-backend
                port:
                  number: 8000
