apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aqis-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aqis-secret-store
  target:
    name: aqis-secrets
    creationPolicy: Owner
  data:
    - secretKey: AQIS_GATEWAY_API_KEY
      remoteRef:
        key: aqis/production
        property: AQIS_GATEWAY_API_KEY
